const BASE_AVATARS={a01:'avatar-kyuchuka-male-01.png',a02:'avatar-kyuchuka-female-01.png',a03:'avatar-kyuchuka-male-02.png',a04:'avatar-kyuchuka-female-02.png',a05:'avatar-world-male-01.png',a06:'avatar-world-male-02.png',a07:'avatar-world-female-01.png',a08:'avatar-world-female-02.png'};
let selectedSignupAvatar='a01';
function avatarSrc(key){return BASE_AVATARS[key]||BASE_AVATARS.a01}
function selectSignupAvatar(key){if(!BASE_AVATARS[key])return;selectedSignupAvatar=key;document.querySelectorAll('.avatar-choice').forEach(x=>x.classList.toggle('selected',x.dataset.avatar===key))}
function syncSignupAvatars(){const side=E('signupSide')?.value||'Кючука';const kyuchuka=side==='Кючука';document.querySelectorAll('.avatar-choice').forEach(x=>x.classList.toggle('hidden',x.dataset.side!==side));const allowed=kyuchuka?['a01','a02','a03','a04']:['a05','a06','a07','a08'];if(!allowed.includes(selectedSignupAvatar))selectSignupAvatar(allowed[0])}
async function syncCharacterEquipment(){if(!currentUser)return;const cap=E('equipmentCapTop'),chain=E('equipmentChainTop');if(!cap||!chain)return;cap.classList.add('hidden');chain.classList.add('hidden');const {data,error}=await sb.from('inventory').select('equipped,items(name)').eq('user_id',currentUser.id).eq('equipped',true);if(error)return;for(const row of data||[]){const name=row.items?.name;if(name==='Каскет „Шефа“')cap.classList.remove('hidden');if(name==='Златист ланец')chain.classList.remove('hidden')}}
const originalSignup=signup;
signup=async function(){if(busySignup)return;let username=E('signupName').value.trim(),email=E('signupEmail').value.trim(),password=E('signupPass').value,side=E('signupSide').value,avatar_key=selectedSignupAvatar;if(username.length<3)return message('Името трябва да е поне 3 символа.');if(password.length<6)return message('Паролата трябва да е поне 6 символа.');busySignup=true;E('signupBtn').disabled=true;E('signupBtn').textContent='СЪЗДАВАМ...';const {data,error}=await sb.auth.signUp({email,password,options:{emailRedirectTo:location.origin,data:{username,side,avatar_key}}});busySignup=false;E('signupBtn').disabled=false;E('signupBtn').textContent='СЪЗДАЙ ГЕРОЙ';if(error)return message(bgError(error));if(data.session)await enterGame(data.user);else message('Героят е създаден. Провери имейла си за потвърждение, после влез.',true)};
const originalLoadProfile=loadProfile;
loadProfile=async function(){await originalLoadProfile();if(!currentProfile)return;const avatar=E('characterAvatarTop'),stack=E('characterStackTop');if(!avatar||!stack)return;avatar.src=avatarSrc(currentProfile.avatar_key);avatar.alt='Аватар на '+currentProfile.username;stack.classList.remove('hidden');await syncCharacterEquipment()};
document.addEventListener('DOMContentLoaded',()=>{selectSignupAvatar('a01');syncSignupAvatars();E('signupSide')?.addEventListener('change',syncSignupAvatars)});
