const BASE_AVATARS={a01:'avatar-kyuchuka-male-01.png',a02:'avatar-kyuchuka-female-01.png'};
let selectedSignupAvatar='a01';
function avatarSrc(key){return BASE_AVATARS[key]||BASE_AVATARS.a01}
function selectSignupAvatar(key){if(!BASE_AVATARS[key])return;selectedSignupAvatar=key;document.querySelectorAll('.avatar-choice').forEach(x=>x.classList.toggle('selected',x.dataset.avatar===key))}
function syncSignupAvatars(){const side=E('signupSide')?.value||'Кючука';const box=E('signupAvatarField');if(!box)return;box.classList.toggle('hidden',side!=='Кючука');const note=E('worldAvatarNote');if(note)note.classList.toggle('hidden',side==='Кючука')}
const originalSignup=signup;
signup=async function(){if(busySignup)return;let username=E('signupName').value.trim(),email=E('signupEmail').value.trim(),password=E('signupPass').value,side=E('signupSide').value,avatar_key=side==='Кючука'?selectedSignupAvatar:'a01';if(username.length<3)return message('Името трябва да е поне 3 символа.');if(password.length<6)return message('Паролата трябва да е поне 6 символа.');busySignup=true;E('signupBtn').disabled=true;E('signupBtn').textContent='СЪЗДАВАМ...';const {data,error}=await sb.auth.signUp({email,password,options:{emailRedirectTo:location.origin,data:{username,side,avatar_key}}});busySignup=false;E('signupBtn').disabled=false;E('signupBtn').textContent='СЪЗДАЙ ГЕРОЙ';if(error)return message(bgError(error));if(data.session)await enterGame(data.user);else message('Героят е създаден. Провери имейла си за потвърждение, после влез.',true)};
const originalLoadProfile=loadProfile;
loadProfile=async function(){await originalLoadProfile();if(!currentProfile)return;const avatar=document.getElementById('characterAvatarTop');if(!avatar)return;if(currentProfile.side==='Кючука'){avatar.src=avatarSrc(currentProfile.avatar_key);avatar.alt='Аватар на '+currentProfile.username;avatar.classList.remove('hidden')}else{avatar.classList.add('hidden')}};
document.addEventListener('DOMContentLoaded',()=>{selectSignupAvatar('a01');syncSignupAvatars();E('signupSide')?.addEventListener('change',syncSignupAvatars)});
