const SUPABASE_URL='https://ntpiiavbqdgnigrzbxqx.supabase.co',SUPABASE_KEY='sb_publishable_AWTR3OL7_651xJXylWy2yg_gtgwgOdW';const sb=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);let currentUser=null,currentProfile=null,busySignup=false,fightBusy=false,currentActivity=null,activityTick=null,fanTick=null;
function E(id){return document.getElementById(id)} function escapeHtml(s){return String(s??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]))}
function showAuth(t){let l=t==='login';E('loginForm').classList.toggle('hidden',!l);E('signupForm').classList.toggle('hidden',l);E('tabLogin').classList.toggle('primary',l);E('tabSignup').classList.toggle('primary',!l);E('authMessage').innerHTML=''}
function message(text,ok=false){E('authMessage').innerHTML=`<div class="msg ${ok?'ok':'err'}">${escapeHtml(text)}</div>`}
function bgError(err){let m=String(err?.message||err||'').toLowerCase();if(m.includes('rate limit'))return 'Направени са твърде много регистрации за кратко време. Изчакай малко и опитай отново.';if(m.includes('already registered'))return 'Този имейл вече е регистриран. Използвай „Вход“.';if(m.includes('invalid login'))return 'Грешен имейл или парола.';if(m.includes('email not confirmed'))return 'Първо потвърди имейла си от писмото за регистрация.';if(m.includes('password'))return 'Провери паролата — трябва да е поне 6 символа.';return err?.message||'Възникна грешка. Опитай отново.'}
async function signup(){if(busySignup)return;let username=E('signupName').value.trim(),email=E('signupEmail').value.trim(),password=E('signupPass').value,side=E('signupSide').value;if(username.length<3)return message('Името трябва да е поне 3 символа.');if(password.length<6)return message('Паролата трябва да е поне 6 символа.');busySignup=true;E('signupBtn').disabled=true;E('signupBtn').textContent='СЪЗДАВАМ...';const {data,error}=await sb.auth.signUp({email,password,options:{emailRedirectTo:location.origin,data:{username,side}}});busySignup=false;E('signupBtn').disabled=false;E('signupBtn').textContent='СЪЗДАЙ ГЕРОЙ';if(error)return message(bgError(error));if(data.session)await enterGame(data.user);else message('Героят е създаден. Провери имейла си за потвърждение, после влез.',true)}
async function login(){E('loginBtn').disabled=true;const {data,error}=await sb.auth.signInWithPassword({email:E('loginEmail').value.trim(),password:E('loginPass').value});E('loginBtn').disabled=false;if(error)return message(bgError(error));await enterGame(data.user)}
async function logout(){await sb.auth.signOut();currentUser=currentProfile=null;E('game').classList.add('hidden');E('authBox').classList.remove('hidden');message('Излезе от играта.',true)}
async function enterGame(user){currentUser=user;E('authBox').classList.add('hidden');E('game').classList.remove('hidden');await refreshAll();history.replaceState(null,'',location.pathname+location.search)}
function openPanel(id,btn){document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));E(id).classList.add('active');document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('active'));btn.classList.add('active');if(id==='shopPanel')loadShop();if(id==='invPanel')loadInventory();if(id==='fanPanel')loadFanBattles();if(id==='premiumPanel')loadPremiumShop()}
async function loadProfile(){await sb.rpc('regen_me');const [{data,error},{data:gear}]=await Promise.all([sb.from('profiles').select('*').eq('id',currentUser.id).single(),sb.from('inventory').select('items(attack_bonus,strength_bonus,defense_bonus,luck_bonus)').eq('user_id',currentUser.id).eq('equipped',true)]);if(error){E('log').textContent='Проблем с профила: '+bgError(error);return}currentProfile=data;const bonus=(gear||[]).reduce((a,v)=>{const i=v.items||{};a.strength+=(i.strength_bonus||0)+(i.attack_bonus||0);a.defense+=i.defense_bonus||0;a.luck+=i.luck_bonus||0;return a},{strength:0,defense:0,luck:0});for(const k of ['username','level','respect','money','hp','energy'])E(k).textContent=data[k];E('strength').textContent=data.strength+bonus.strength;E('defense').textContent=data.defense+bonus.defense;E('luck').textContent=data.luck+bonus.luck;E('sideLine').textContent=data.side;E('sideLine').className='badge '+(data.side==='The World'?'world':'');E('wl').textContent=`${data.wins} победи / ${data.losses} загуби`;E('energyFill').style.width=data.energy+'%';E('footballRespect').textContent=data.football_respect||0;E('clubStat').textContent=clubLabel(data.football_club,data.football_choice_locked);E('premiumCoins').textContent=data.premium_coins||0;E('premiumBalance').textContent=data.premium_coins||0;E('prestigePoints').textContent=data.prestige_points||0;const un=E('username');un.classList.remove('name-gold','name-neon');if(data.name_style)un.classList.add('name-'+data.name_style);E('vipTop').classList.toggle('hidden',!data.vip_badge);const pa=E('premiumAvatarTop');pa.classList.toggle('hidden',!data.premium_avatar);if(data.premium_avatar)pa.textContent=data.premium_avatar;renderClubInfo()}
function styledName(p){const cls=p.name_style==='gold'?'name-gold':p.name_style==='neon'?'name-neon':'';return `${p.premium_avatar?`<span class="premium-avatar" style="width:34px;height:34px;font-size:19px">${escapeHtml(p.premium_avatar)}</span>`:''}<b class="${cls}">${escapeHtml(p.username)}</b>${p.vip_badge?'<span class="vip-mark">👑 VIP</span>':''}`;}
async function loadPlayers(){const {data,error}=await sb.from('profiles').select('id,username,side,level,respect,wins,losses,premium_avatar,name_style,vip_badge').neq('id',currentUser.id).order('respect',{ascending:false}).limit(20);if(error){E('players').innerHTML=`<div class="msg err">${escapeHtml(bgError(error))}</div>`;return}E('players').innerHTML=data.length?data.map(p=>`<div class="player"><div>${styledName(p)} ${p.side==='Кючука'?'<span class="badge">Кючука</span>':'<span class="badge world">The World</span>'}<small>Ниво ${p.level} · Респект ${p.respect} · ${p.wins}/${p.losses}</small></div><button class="primary fight-btn" data-name="${escapeHtml(p.username)}" onclick="fight('${p.id}',this)">НАПАДНИ ⚡ 20</button></div>`).join(''):'<div class="msg">Още няма други играчи.</div>'}
async function loadLeaderboard(){const {data}=await sb.from('profiles').select('id,username,side,level,respect,wins,premium_avatar,name_style,vip_badge').order('respect',{ascending:false}).limit(10);E('leaderboard').innerHTML=(data||[]).map((p,i)=>`<div class="player"><div class="rank">${i+1}</div><div style="flex:1"><span class="${p.id===currentUser.id?'me':''}">${styledName(p)}</span><small>${escapeHtml(p.side)} · Ниво ${p.level} · ${p.wins} победи</small></div><b>${p.respect} 😎</b></div>`).join('')}
function showBattleResult(data,name){const overlay=E('battleOverlay'),modal=E('battleModal'),title=E('battleTitle'),body=E('battleBody');if(!overlay||!modal||!title||!body){alert(data?.won?`🏆 ПОБЕДА срещу ${name}!`:`💥 ЗАГУБА срещу ${name}!`);return}modal.className='battlemodal '+(data.won?'win':'lose');title.textContent=data.won?'🏆 ПОБЕДА!':'💥 ЗАГУБА!';body.innerHTML=`<div class="msg">${data.won?`Размаза <b>${escapeHtml(name)}</b>.`:`<b>${escapeHtml(name)}</b> те прати да преосмислиш екипировката.`}</div><div class="battleline"><span>⚔️ Твоя сила в боя</span><b>${data.attacker_score}</b></div><div class="battleline"><span>🛡️ Сила на противника</span><b>${data.defender_score}</b></div><div class="battleline"><span>😎 Респект</span><b>${data.won?'+'+data.respect:'0'}</b></div><div class="battleline"><span>💶 Пари</span><b>${data.won?'+'+data.money+' €':'0 €'}</b></div><div class="battleline"><span>⚡ Изразходвана енергия</span><b>-20</b></div>`;overlay.classList.remove('hidden');overlay.style.display='grid';overlay.style.zIndex='2147483647'}
function closeBattleResult(){const overlay=E('battleOverlay');if(!overlay)return;overlay.classList.add('hidden');overlay.style.display='';overlay.style.zIndex=''}
async function fight(id,btn){if(fightBusy)return;const name=btn?.dataset?.name||'противника';if(!currentProfile||currentProfile.energy<20){E('log').textContent='⚡ Трябват ти поне 20 енергия за бой.';return}fightBusy=true;document.querySelectorAll('.fight-btn').forEach(b=>b.disabled=true);if(btn)btn.textContent='БОЯТ ТЕЧЕ...';E('log').textContent='⚔️ Нападаш '+name+'...';const {data,error}=await sb.rpc('fight_player',{opponent:id});if(error){fightBusy=false;E('log').textContent='Боят не можа да започне: '+bgError(error);if(E('streets')?.classList.contains('active'))await loadStreetLocation(selectedStreetLocation);else await loadPlayers();return}E('log').textContent=data.won?`🏆 ПОБЕДА срещу ${name}!\n+${data.respect} респект · +${data.money} €\n⚡ -20 енергия\nСила на боя: ${data.attacker_score} срещу ${data.defender_score}`:`💥 ${name} те би.\n⚡ -20 енергия\nСила на боя: ${data.attacker_score} срещу ${data.defender_score}\nСледващия път по-малко самочувствие, повече екипировка.`;await refreshAll();fightBusy=false;showBattleResult(data,name)}
