function clubLabel(c,locked=true){if(!locked)return 'Неизбрана';return c==='botev'?'Каравелов':c==='lokomotiv'?'Тролей':'Без агитка'}
function renderClubInfo(){if(!currentProfile)return;const choose=E('clubChooser'),info=E('clubInfo');if(!currentProfile.football_choice_locked){choose.classList.remove('hidden');info.innerHTML='';return}choose.classList.add('hidden');if(currentProfile.football_club==='botev')info.innerHTML=`<div class="msg"><span class="clubtag botev">🟡⚫ КАРАВЕЛОВ</span><br><br>Футболен респект: <b>${currentProfile.football_respect||0}</b></div>`;else if(currentProfile.football_club==='lokomotiv')info.innerHTML=`<div class="msg"><span class="clubtag lokomotiv">⚫⚪ ТРОЛЕЙ</span><br><br>Футболен респект: <b>${currentProfile.football_respect||0}</b></div>`;else info.innerHTML='<div class="msg">🤷 Избра да не участваш в агитките.</div>'}
async function chooseClub(club){const labels={botev:'Каравелов',lokomotiv:'Тролей',none:'без агитка'};if(!confirm(`Избираш ${labels[club]}. Този избор е окончателен за героя. Продължаваме?`))return;const {error}=await sb.rpc('set_football_club',{p_club:club});if(error){E('log').textContent='⚽ '+bgError(error);return}E('log').textContent='⚽ Изборът е записан.';await refreshAll();await loadFanBattles()}
async function loadFanBattles(){
 if(!currentUser)return;renderClubInfo();
 const {data:battles,error}=await sb.from('fan_battles').select('*').order('created_at',{ascending:false}).limit(5);if(error){E('fanBattleBox').innerHTML=`<div class="msg err">${escapeHtml(bgError(error))}</div>`;return}
 let active=(battles||[]).find(b=>b.status==='open');if(active&&new Date(active.ends_at)<=new Date()){await sb.rpc('finish_fan_battle',{p_battle_id:active.id});return loadFanBattles()}
 if(active){const {data:entries}=await sb.from('fan_battle_entries').select('user_id,club').eq('battle_id',active.id);const b=(entries||[]).filter(x=>x.club==='botev').length,l=(entries||[]).filter(x=>x.club==='lokomotiv').length,joined=(entries||[]).some(x=>x.user_id===currentUser.id);const left=Math.max(0,new Date(active.ends_at)-Date.now()),m=Math.floor(left/60000),sec=Math.floor((left%60000)/1000);E('fanBattleBox').innerHTML=`<div class="fanbattle"><div class="fanvs"><div><span class="clubtag botev">КАРАВЕЛОВ</span><div class="fanbig">${b}</div><small>записани</small></div><b>VS</b><div><span class="clubtag lokomotiv">ТРОЛЕЙ</span><div class="fanbig">${l}</div><small>записани</small></div></div><p style="text-align:center">⏳ ${m}:${String(sec).padStart(2,'0')} до края</p>${currentProfile?.football_choice_locked&&currentProfile.football_club!=='none'?`<button class="primary" style="width:100%" ${joined?'disabled':''} onclick="joinFanBattle(${active.id})">${joined?'ЗАПИСАН СИ':'ВКЛЮЧИ СЕ В СБЛЪСЪКА'}</button>`:'<div class="tiny" style="text-align:center">За участие трябва да си избрал Каравелов или Тролей.</div>'}</div>`
 }else{E('fanBattleBox').innerHTML=`<div class="msg">В момента няма активен сблъсък.</div>${currentProfile?.football_choice_locked&&currentProfile.football_club!=='none'?'<div class="row"><button class="primary" onclick="createFanBattle(10)">10 МИН.</button><button class="primary" onclick="createFanBattle(30)">30 МИН.</button><button class="primary" onclick="createFanBattle(60)">60 МИН.</button></div>':'<div class="tiny">Избери агитка, за да можеш да организираш игрови сблъсък.</div>'}`}
 const finished=(battles||[]).filter(b=>b.status==='finished').slice(0,3);if(finished.length)E('fanBattleBox').innerHTML+=`<h3>Последни резултати</h3>`+finished.map(b=>`<div class="event"><div><b>${b.winner==='botev'?'🟡⚫ Каравелов':b.winner==='lokomotiv'?'⚫⚪ Тролей':'🤝 Равенство'}</b><small>Каравелов ${b.botev_score} : ${b.lokomotiv_score} Тролей</small></div></div>`).join('')
}
async function createFanBattle(minutes){const {data,error}=await sb.rpc('create_fan_battle',{p_duration_minutes:minutes});if(error){E('log').textContent='🔥 '+bgError(error);return}E('log').textContent=`🔥 Организира виртуален сблъсък за ${minutes} минути.`;await loadFanBattles()}
async function joinFanBattle(id){const {data,error}=await sb.rpc('join_fan_battle',{p_battle_id:id});if(error){E('log').textContent='⚽ '+bgError(error);return}E('log').textContent=`⚽ Записа се за агитката. Бойна мощ: ${data.power}.`;await loadFanBattles()}
