async function loadMassBrawls(){
 const box=E('massBrawlBox');if(!box||!currentUser)return;
 await sb.rpc('ensure_mass_brawls');
 const now=new Date().toISOString();
 const {data:brawls,error}=await sb.from('mass_brawls').select('*').gte('ends_at',now).order('starts_at').limit(6);
 if(error){box.innerHTML=`<div class="msg err">${escapeHtml(bgError(error))}</div>`;return}
 const visible=[];
 for(const slot of ['12:30','19:30']){const next=(brawls||[]).find(b=>new Date(b.starts_at).toLocaleTimeString('bg-BG',{timeZone:'Europe/Sofia',hour:'2-digit',minute:'2-digit',hour12:false})===slot);if(next)visible.push(next)}
 visible.sort((a,b)=>new Date(a.starts_at)-new Date(b.starts_at));
 const ids=visible.map(b=>b.id);let entries=[];if(ids.length){const r=await sb.from('mass_brawl_entries').select('*').in('brawl_id',ids);entries=r.data||[]}
 box.classList.add('mass-brawl-slots');box.innerHTML=visible.map(b=>renderMassBrawlCard(b,entries.filter(e=>e.brawl_id===b.id))).join('')||'<div class="msg">Няма предстоящо меле.</div>';
}
function massBrawlTime(ts){return new Date(ts).toLocaleString('bg-BG',{timeZone:'Europe/Sofia',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}
function renderMassBrawlCard(b,entries){const mine=entries.find(e=>e.user_id===currentUser.id),now=Date.now(),start=new Date(b.starts_at).getTime(),end=new Date(b.ends_at).getTime(),live=now>=start&&now<end&&b.status!=='finished';if(live&&mine)return `<div class="msg"><b>🔴 МЕЛЕТО Е LIVE · ${massBrawlTime(b.starts_at)}</b><br><span class="tiny">Участници: ${entries.length} · твоето HP: ${mine.battle_hp}/${mine.battle_max_hp}</span><br><button class="primary" style="margin-top:8px" onclick="openMassBrawl(${b.id})">ВЛЕЗ В МЕЛЕТО</button></div>`;if(live)return `<div class="msg"><b>🔴 Мелето в ${massBrawlTime(b.starts_at)} вече тече</b><br><span class="tiny">Записването е приключило · участници: ${entries.length}</span></div>`;if(now<start)return `<div class="msg"><b>🥊 Меле · ${massBrawlTime(b.starts_at)}</b><br><span class="tiny">Записани: ${entries.length} · 3 мин.</span><br>${mine?'<button disabled style="margin-top:8px">✅ ЗАПИСАН СИ</button>':`<button class="primary" style="margin-top:8px" onclick="joinMassBrawl(${b.id})">ЗАПИШИ СЕ ЗА ${new Date(b.starts_at).toLocaleTimeString('bg-BG',{timeZone:'Europe/Sofia',hour:'2-digit',minute:'2-digit'})}</button>`}</div>`;return ''}
async function joinMassBrawl(id){const {error}=await sb.rpc('join_mass_brawl',{p_brawl_id:id});if(error)return alert('❌ '+bgError(error));await loadMassBrawls()}
function closeMassBrawl(){E('massBrawlArenaOverlay')?.classList.add('hidden');loadMassBrawls()}
async function openMassBrawl(id){const overlay=E('massBrawlArenaOverlay'),arena=E('massBrawlArena');if(!overlay||!arena)return;overlay.classList.remove('hidden');arena.innerHTML='<div class="msg">Зареждане на мелето…</div>';const [{data:entries},{data:events}]=await Promise.all([sb.from('mass_brawl_entries').select('*').eq('brawl_id',id),sb.from('mass_brawl_events').select('*').eq('brawl_id',id).order('id',{ascending:false}).limit(40)]);const ids=[...new Set((entries||[]).map(e=>e.user_id))],names=new Map();if(ids.length){const {data:p}=await sb.from('profiles').select('id,username').in('id',ids);(p||[]).forEach(x=>names.set(x.id,x.username))}const mine=(entries||[]).find(e=>e.user_id===currentUser.id),targets=(entries||[]).filter(e=>e.user_id!==currentUser.id&&!e.knocked_out);arena.innerHTML=`<div style="display:flex;justify-content:space-between;gap:12px;align-items:center"><h2 style="margin:0">🥊 Масово меле</h2><button onclick="closeMassBrawl()">✕ ЗАТВОРИ</button></div><div class="msg" style="margin-top:12px"><b>🔴 МЕЛЕТО Е В ХОД</b><br>❤️ ${mine?.battle_hp||0}/${mine?.battle_max_hp||0} · участници: ${(entries||[]).length}</div>${mine&&!mine.knocked_out?`<div class="field"><label>Противник</label><select id="massBrawlTarget">${targets.map(t=>`<option value="${t.user_id}">${escapeHtml(names.get(t.user_id)||'Играч')} · ❤️ ${t.battle_hp}</option>`).join('')}</select></div><button class="primary" onclick="attackMassBrawl(${id})">АТАКУВАЙ</button>`:'<div class="msg err">💀 Нокаутиран си.</div>'}<h3>📡 Live log</h3><div class="log">${(events||[]).map(e=>escapeHtml(e.message)).join('<br>')||'Мелето започва…'}</div>`}
async function attackMassBrawl(id){const target=E('massBrawlTarget')?.value;if(!target)return;const {error}=await sb.rpc('attack_mass_brawl',{p_brawl_id:id,p_target_user_id:target});if(error)return alert('⏳ '+bgError(error));await openMassBrawl(id)}
