let playerProfileBusy=false;
const NEIGHBORHOOD_BOT_IDS=new Set(['00000000-0000-4000-8000-000000000101','00000000-0000-4000-8000-000000000102','00000000-0000-4000-8000-000000000103','00000000-0000-4000-8000-000000000104']);
const NEIGHBORHOOD_BOT_AVATARS={
'00000000-0000-4000-8000-000000000101':'npc-krasi-debeliya.png',
'00000000-0000-4000-8000-000000000102':'npc-dancho-zhultiya.png',
'00000000-0000-4000-8000-000000000103':'npc-bobi-reisa.png',
'00000000-0000-4000-8000-000000000104':'npc-bat-tomi.png'
};
const styledNameWithoutProfile=styledName;
styledName=function(p){return `<span class="player-name-link" data-player-id="${escapeHtml(p.id||'')}">${styledNameWithoutProfile(p)}</span>`};
function playerTalentLabel(n){return n>=10?'ЛЕГЕНДА':n>=6?'ВЕТЕРАН':n>=3?'НАПРЕДНАЛ':'НОВАК'}
function playerProfileAvatar(p){if(p.premium_avatar)return `<div class="player-profile-premium-avatar">${escapeHtml(p.premium_avatar)}</div>`;const src=NEIGHBORHOOD_BOT_AVATARS[p.id]||(typeof avatarSrc==='function'?avatarSrc(p.avatar_key):'avatar-kyuchuka-male-01.png');return `<img class="player-profile-avatar" src="${escapeHtml(src)}" alt="" style="visibility:hidden" onload="this.style.visibility='visible'" onerror="this.onerror=null;this.src='avatar-kyuchuka-male-01.png'">`}
async function openPlayerProfile(id){if(!id||playerProfileBusy)return;const overlay=E('playerProfileOverlay'),body=E('playerProfileBody');if(!overlay||!body)return;playerProfileBusy=true;body.innerHTML='<div class="player-profile-loading">Зареждам кварталното досие...</div>';overlay.classList.remove('hidden');const {data:p,error}=await sb.from('profiles').select('id,username,side,level,respect,wins,losses,strength,defense,luck,avatar_key,premium_avatar,name_style,vip_badge,talent_brawler,talent_hustler,talent_local').eq('id',id).single();playerProfileBusy=false;if(error||!p){body.innerHTML='<div class="msg err">Профилът не може да бъде зареден.</div>';return}const nameClass=p.name_style==='gold'?'name-gold':p.name_style==='neon'?'name-neon':'';const stats=`<div class="player-profile-stats"><div><span>🏆 Победи</span><b>${p.wins}</b></div><div><span>💥 Загуби</span><b>${p.losses}</b></div><div><span>💪 Сила</span><b>${p.strength}</b></div><div><span>🛡️ Защита</span><b>${p.defense}</b></div><div><span>🍀 Късмет</span><b>${p.luck}</b></div></div>`;body.innerHTML=`<div class="player-profile-head">${playerProfileAvatar(p)}<div class="player-profile-identity"><div class="player-profile-name ${nameClass}">${escapeHtml(p.username)} ${p.vip_badge?'<span class="vip-mark">👑 VIP</span>':''}${NEIGHBORHOOD_BOT_IDS.has(p.id)?'<span class="npc-mark">NPC</span>':''}</div><div class="badge ${p.side==='The World'?'world':''}">${escapeHtml(p.side)}</div><small>Ниво ${p.level} · 😎 ${p.respect} респект</small>${stats}</div></div><div class="player-profile-talents"><h3>🏘️ Квартални умения</h3>${[['👊 Батка',p.talent_brawler],['😎 Тарикат',p.talent_hustler],['🏘️ Квартален',p.talent_local]].map(([name,n])=>`<div class="profile-talent-row"><span>${name}<small>${playerTalentLabel(n)}</small></span><b>${n}/10</b></div>`).join('')}</div>`}
function closePlayerProfile(){E('playerProfileOverlay')?.classList.add('hidden')}
document.addEventListener('click',e=>{const target=e.target.closest('[data-player-id]');if(!target||e.target.closest('button'))return;e.preventDefault();openPlayerProfile(target.dataset.playerId)});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closePlayerProfile()});