async function loadShop(){
 const [{data:items},{data:inv}]=await Promise.all([sb.from('items').select('*').order('price'),sb.from('inventory').select('item_id,quantity').eq('user_id',currentUser.id)]);
 const counts=new Map((inv||[]).map(x=>[x.item_id,x.quantity||1]));
 const groups=[['⚔️ Оръжия',(items||[]).filter(i=>i.item_type==='weapon')],['⚡ Енергия и храна',(items||[]).filter(i=>i.item_type==='consumable')],['🧥 Екипировка',(items||[]).filter(i=>i.item_type==='equipment')]];
 E('shop').innerHTML=groups.map(([title,list])=>`<div style="margin:8px 0 18px"><h3 style="margin:0 0 9px;color:var(--gold)">${title}</h3><div class="shop">${list.map(i=>{const owned=counts.has(i.id),cons=i.item_type==='consumable',stackable=cons||i.consumed_on_use;const stats=[i.attack_bonus?`⚔️ +${i.attack_bonus}`:'',i.strength_bonus?`💪 +${i.strength_bonus}`:'',i.defense_bonus?`🛡️ +${i.defense_bonus}`:'',i.luck_bonus?`🍀 +${i.luck_bonus}`:'',i.energy_restore?`⚡ +${i.energy_restore}`:''].filter(Boolean).join(' · ')||'Без бонус';return `<div class="item"><div><b>${escapeHtml(i.name)} ${stackable&&owned?`×${counts.get(i.id)}`:''}</b><small>${escapeHtml(i.description)} · ${escapeHtml(i.rarity||'common')}<br>${stats}</small></div><button class="${(!owned||stackable)?'gold':''}" ${owned&&!stackable?'disabled':''} onclick="buy(${i.id})">${owned&&!stackable?'КУПЕНО':i.price+' €'}</button></div>`}).join('')}</div></div>`).join('')
}
async function buy(id){const {data,error}=await sb.rpc('buy_item',{target_item:id});if(error){E('log').textContent='🛒 '+bgError(error);alert('❌ '+bgError(error));return}E('log').textContent='🛒 Купи '+data.item+'.';alert('✅ Купи '+data.item+' успешно!');await refreshAll();await loadShop();await loadInventory()}
async function loadInventory(){
 const {data,error}=await sb.from('inventory').select('item_id,equipped,quantity,items(id,name,slot,item_type,energy_restore,attack_bonus,strength_bonus,defense_bonus,luck_bonus,description,rarity,combat_effect,combat_effect_value,consumed_on_use)').eq('user_id',currentUser.id);
 if(error){E('inventory').innerHTML=`<div class="msg err">${escapeHtml(bgError(error))}</div>`;return}
 E('inventory').innerHTML=data?.length?data.map(v=>{let i=v.items,cons=i.item_type==='consumable',combatUse=i.item_type==='weapon'&&i.consumed_on_use;const stats=[i.attack_bonus?`⚔️ +${i.attack_bonus}`:'',i.strength_bonus?`💪 +${i.strength_bonus}`:'',i.defense_bonus?`🛡️ +${i.defense_bonus}`:'',i.luck_bonus?`🍀 +${i.luck_bonus}`:'',i.energy_restore?`⚡ +${i.energy_restore}`:'',i.combat_effect==='burn'?`🔥 +${i.combat_effect_value} специален ефект`:''].filter(Boolean).join(' · ')||'Без бонус';let button=cons?`<button class="gold" onclick="useEnergy(${i.id})">ИЗПОЛЗВАЙ +${i.energy_restore} ⚡</button>`:`<button class="${v.equipped?'':'blue'}" ${v.equipped?'disabled':''} onclick="equip(${i.id})">${v.equipped?'ЕКИПИРАН':'ЕКИПИРАЙ'}</button>`;return `<div class="item"><div><b>${escapeHtml(i.name)} ${(cons||combatUse)?`×${v.quantity||1}`:''} ${v.equipped?'✅':''}</b><small>${escapeHtml(i.description)}<br>${stats}</small></div>${button}</div>`}).join(''):'<div class="msg">Още нямаш нищо. Събота пазар те очаква.</div>'
}
async function equip(id){const {data,error}=await sb.rpc('equip_item',{target_item:id});if(error){E('log').textContent='🎒 '+bgError(error);return}E('log').textContent='🎒 Екипира: '+data.item+'. Бонусите вече участват в боя.';await loadInventory();await refreshAll()}
async function useEnergy(id){const {data,error}=await sb.rpc('use_energy_item',{p_item:id});if(error){E('log').textContent='⚡ '+bgError(error);return}E('log').textContent=`⚡ Използва ${data.item}. +${data.energy_restored} енергия.`;await refreshAll();await loadInventory();await loadShop()}
