-- Interactive real-time gang battles
-- Additive migration only. Battle duration is exactly 2 minutes after a 5-minute registration window.

alter table public.gang_battles add column if not exists registration_ends_at timestamptz;
alter table public.gang_battles add column if not exists finished_at timestamptz;
alter table public.gang_battles add column if not exists finish_reason text;
alter table public.gang_battles add column if not exists challenger_damage integer not null default 0;
alter table public.gang_battles add column if not exists defender_damage integer not null default 0;

alter table public.gang_battle_entries add column if not exists battle_hp integer not null default 100;
alter table public.gang_battle_entries add column if not exists battle_max_hp integer not null default 100;
alter table public.gang_battle_entries add column if not exists total_damage integer not null default 0;
alter table public.gang_battle_entries add column if not exists knocked_out boolean not null default false;
alter table public.gang_battle_entries add column if not exists last_attack_at timestamptz;
alter table public.gang_battle_entries add column if not exists molotov_used boolean not null default false;

create table if not exists public.gang_battle_events (
 id bigint generated by default as identity primary key,
 battle_id bigint not null references public.gang_battles(id) on delete cascade,
 actor_id uuid references public.profiles(id),
 target_id uuid references public.profiles(id),
 event_type text not null,
 message text not null,
 damage integer not null default 0,
 target_hp integer,
 special_effect text,
 weapon_item_id bigint references public.items(id),
 payload jsonb not null default '{}'::jsonb,
 created_at timestamptz not null default now()
);
create index if not exists gang_battle_events_battle_idx on public.gang_battle_events(battle_id,id);
alter table public.gang_battle_events enable row level security;
grant select on public.gang_battle_events to authenticated;

do $$ begin
 if not exists(select 1 from pg_policies where schemaname='public' and tablename='gang_battle_events' and policyname='gang battle participants read live log') then
  create policy "gang battle participants read live log" on public.gang_battle_events for select to authenticated
  using(exists(select 1 from public.gang_members gm join public.gang_battles gb on gb.id=gang_battle_events.battle_id where gm.user_id=(select auth.uid()) and gm.gang_id in(gb.challenger_gang_id,gb.defender_gang_id)));
 end if;
end $$;

do $$ begin
 if exists(select 1 from pg_publication where pubname='supabase_realtime') then
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='gang_battles') then alter publication supabase_realtime add table public.gang_battles; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='gang_battle_entries') then alter publication supabase_realtime add table public.gang_battle_entries; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='gang_battle_events') then alter publication supabase_realtime add table public.gang_battle_events; end if;
 end if;
end $$;

create or replace function public.create_gang_battle(p_defender_gang_id bigint,p_duration_minutes integer default 2)
returns jsonb language plpgsql security definer set search_path='public' as $$
declare gm public.gang_members; g1 public.gangs; g2 public.gangs; bid bigint; v_start timestamptz; v_end timestamptz;
begin
 if auth.uid() is null then raise exception 'not authenticated'; end if;
 select * into gm from public.gang_members where user_id=auth.uid();
 if gm.user_id is null then raise exception 'Не си в банда.'; end if;
 if gm.role<>'leader' then raise exception 'Само лидерът може да организира битка.'; end if;
 select * into g1 from public.gangs where id=gm.gang_id; select * into g2 from public.gangs where id=p_defender_gang_id;
 if g2.id is null or g2.id=g1.id then raise exception 'Невалиден противник.'; end if;
 if exists(select 1 from public.gang_battles where status in('open','live') and (challenger_gang_id in(g1.id,g2.id) or defender_gang_id in(g1.id,g2.id))) then raise exception 'Една от бандите вече има активна битка.'; end if;
 v_start:=now()+interval '5 minutes'; v_end:=v_start+interval '2 minutes';
 insert into public.gang_battles(challenger_gang_id,defender_gang_id,status,starts_at,registration_ends_at,ends_at,created_by)
 values(g1.id,g2.id,'open',v_start,v_start,v_end,auth.uid()) returning id into bid;
 insert into public.gang_battle_events(battle_id,actor_id,event_type,message,payload) values(bid,auth.uid(),'created','🔥 '||g1.name||' предизвика '||g2.name||'. Записването е отворено за 5 минути.',jsonb_build_object('starts_at',v_start,'ends_at',v_end));
 return jsonb_build_object('id',bid,'challenger',g1.name,'defender',g2.name,'starts_at',v_start,'ends_at',v_end,'duration_minutes',2,'registration_minutes',5);
end $$;

create or replace function public.join_gang_battle(p_battle_id bigint)
returns jsonb language plpgsql security definer set search_path='public' as $$
declare gm public.gang_members; b public.gang_battles; p public.profiles; pow int; eqatk int:=0; eqstr int:=0; eqdef int:=0; eqluck int:=0; hp_snapshot int;
begin
 if auth.uid() is null then raise exception 'not authenticated'; end if;
 select * into gm from public.gang_members where user_id=auth.uid(); if gm.user_id is null then raise exception 'Не си в банда.'; end if;
 select * into b from public.gang_battles where id=p_battle_id for update;
 if b.id is null or b.status<>'open' or now()>=b.starts_at then raise exception 'Записването за тази битка е приключило.'; end if;
 if gm.gang_id not in(b.challenger_gang_id,b.defender_gang_id) then raise exception 'Твоята банда не участва в тази битка.'; end if;
 if exists(select 1 from public.activities where user_id=auth.uid() and ends_at>now()) then raise exception 'Героят ти е зает.'; end if;
 select * into p from public.profiles where id=auth.uid();
 select coalesce(sum(i.attack_bonus),0),coalesce(sum(i.strength_bonus),0),coalesce(sum(i.defense_bonus),0),coalesce(sum(i.luck_bonus),0) into eqatk,eqstr,eqdef,eqluck from public.inventory v join public.items i on i.id=v.item_id where v.user_id=auth.uid() and v.equipped=true;
 pow:=p.strength+eqstr+eqatk+p.defense+eqdef+floor((p.luck+eqluck)/2.0)::int+(p.level*2);
 hp_snapshot:=greatest(60,least(160,100+((p.defense+eqdef-10)*2)+((p.level-1)*2)));
 insert into public.gang_battle_entries(battle_id,user_id,gang_id,power,battle_hp,battle_max_hp,total_damage,knocked_out,molotov_used) values(b.id,auth.uid(),gm.gang_id,pow,hp_snapshot,hp_snapshot,0,false,false);
 insert into public.gang_battle_events(battle_id,actor_id,event_type,message,target_hp,payload) values(b.id,auth.uid(),'join',p.username||' се записа за битката.',hp_snapshot,jsonb_build_object('gang_id',gm.gang_id,'battle_hp',hp_snapshot));
 return jsonb_build_object('joined',true,'power',pow,'gang_id',gm.gang_id,'battle_hp',hp_snapshot);
exception when unique_violation then raise exception 'Вече участваш в тази битка.';
end $$;

create or replace function public.finish_gang_battle(p_battle_id bigint)
returns jsonb language plpgsql security definer set search_path='public' as $$
declare b public.gang_battles; chp int; dhp int; cdmg int; ddmg int; alive_c int; alive_d int; win bigint; why text;
begin
 if auth.uid() is null then raise exception 'not authenticated'; end if;
 select * into b from public.gang_battles where id=p_battle_id for update;
 if b.id is null then raise exception 'Няма такава битка.'; end if;
 if b.status='finished' then return jsonb_build_object('winner_gang_id',b.winner_gang_id,'challenger_score',b.challenger_score,'defender_score',b.defender_score,'finished',true); end if;
 select coalesce(sum(battle_hp),0),coalesce(sum(total_damage),0),count(*) filter(where not knocked_out) into chp,cdmg,alive_c from public.gang_battle_entries where battle_id=b.id and gang_id=b.challenger_gang_id;
 select coalesce(sum(battle_hp),0),coalesce(sum(total_damage),0),count(*) filter(where not knocked_out) into dhp,ddmg,alive_d from public.gang_battle_entries where battle_id=b.id and gang_id=b.defender_gang_id;
 if alive_c=0 and alive_d>0 then win:=b.defender_gang_id;why:='all_opponents_knocked_out';
 elsif alive_d=0 and alive_c>0 then win:=b.challenger_gang_id;why:='all_opponents_knocked_out';
 elsif now()>=b.ends_at then
  why:='time_limit';
  if chp>dhp then win:=b.challenger_gang_id; elsif dhp>chp then win:=b.defender_gang_id; elsif cdmg>ddmg then win:=b.challenger_gang_id; elsif ddmg>cdmg then win:=b.defender_gang_id; else win:=null; end if;
 else raise exception 'Битката още не е приключила.'; end if;
 update public.gang_battles set status='finished',winner_gang_id=win,challenger_score=chp,defender_score=dhp,challenger_damage=cdmg,defender_damage=ddmg,finished_at=now(),finish_reason=why where id=b.id;
 if win is not null then update public.gangs set respect=respect+5 where id=win; end if;
 insert into public.gang_battle_events(battle_id,event_type,message,payload) values(b.id,'result',case when win is null then '🤝 Битката приключи наравно.' else '🏆 Битката приключи с победител.' end,jsonb_build_object('winner_gang_id',win,'challenger_hp',chp,'defender_hp',dhp,'challenger_damage',cdmg,'defender_damage',ddmg,'reason',why));
 return jsonb_build_object('winner_gang_id',win,'challenger_score',chp,'defender_score',dhp,'challenger_damage',cdmg,'defender_damage',ddmg,'finished',true,'reason',why);
end $$;

create or replace function public.attack_gang_battle(p_battle_id bigint,p_target_user_id uuid,p_weapon_item_id bigint default null)
returns jsonb language plpgsql security definer set search_path='public' as $$
declare b public.gang_battles; a public.gang_battle_entries; t public.gang_battle_entries; ap public.profiles; tp public.profiles; w public.items; qty int:=0; atk int; def int; dmg int; roll numeric; crit boolean:=false; blocked boolean:=false; missed boolean:=false; burn int:=0; hp_after int; msg text; special text:=null; all_down boolean:=false; result jsonb; fists text[]:=array['сваля %s с десен ъперкът','разклаща %s с кроше под брадичката','праща %s на земята с тежък десен','забива лакът и разклаща %s','връхлита върху %s с квартална комбинация'];
begin
 if auth.uid() is null then raise exception 'not authenticated'; end if;
 select * into b from public.gang_battles where id=p_battle_id for update;
 if b.id is null or b.status='finished' then raise exception 'Битката не е активна.'; end if;
 if now()<b.starts_at then raise exception 'Битката още не е започнала.'; end if;
 if now()>=b.ends_at then return public.finish_gang_battle(b.id); end if;
 if b.status='open' then update public.gang_battles set status='live' where id=b.id; end if;
 select * into a from public.gang_battle_entries where battle_id=b.id and user_id=auth.uid() for update;
 if a.user_id is null then raise exception 'Не си записан за тази битка.'; end if;
 if a.knocked_out or a.battle_hp<=0 then raise exception 'Нокаутиран си и не можеш да атакуваш.'; end if;
 if a.last_attack_at is not null and now()<a.last_attack_at+interval '5 seconds' then raise exception 'Изчакай 5 секунди между атаките.'; end if;
 select * into t from public.gang_battle_entries where battle_id=b.id and user_id=p_target_user_id for update;
 if t.user_id is null or t.gang_id=a.gang_id then raise exception 'Избери противников участник.'; end if;
 if t.knocked_out or t.battle_hp<=0 then raise exception 'Този противник вече е нокаутиран.'; end if;
 select * into ap from public.profiles where id=a.user_id; select * into tp from public.profiles where id=t.user_id;
 atk:=ap.strength+floor(ap.luck/3.0)::int+a.power/8; def:=tp.defense+floor(tp.luck/4.0)::int+t.power/10;
 if p_weapon_item_id is not null then
  select i.* into w from public.inventory v join public.items i on i.id=v.item_id where v.user_id=a.user_id and v.item_id=p_weapon_item_id and i.item_type='weapon';
  if w.id is null then raise exception 'Не притежаваш това оръжие.'; end if;
  select quantity into qty from public.inventory where user_id=a.user_id and item_id=w.id for update;
  if coalesce(qty,0)<=0 then raise exception 'Нямаш налично количество.'; end if;
  if lower(w.name)=lower('Молотов') and a.molotov_used then raise exception 'Вече използва Молотов в тази битка.'; end if;
  atk:=atk+w.attack_bonus+w.strength_bonus;
 end if;
 roll:=random();
 if roll<0.10 then missed:=true;dmg:=0;
 elsif roll<0.20 then blocked:=true;dmg:=greatest(1,floor((atk-def)*0.25)::int);
 else dmg:=greatest(2,6+floor(random()*7)::int+floor((atk-def)/5.0)::int);if roll>0.90 then crit:=true;dmg:=dmg+5+floor(random()*5)::int;end if;end if;
 if w.combat_effect='burn' then burn:=greatest(2,w.combat_effect_value);dmg:=dmg+burn;special:='🔥 Огнен ефект +'||burn||' damage'; end if;
 hp_after:=greatest(0,t.battle_hp-dmg);
 if missed then msg:=ap.username||' замахва към '||tp.username||', но пропуска.';
 elsif blocked then msg:=tp.username||' блокира атаката на '||ap.username||'.';
 elsif w.id is null then msg:=ap.username||' '||format(fists[1+floor(random()*array_length(fists,1))::int],tp.username)||'.';
 elsif lower(w.name)=lower('Молотов') then msg:=ap.username||' хвърля Молотов по '||tp.username||' и пламъците избухват.';
 elsif lower(w.name) like '%нож%' then msg:=ap.username||' налита с '||w.name||' и порязва '||tp.username||'.';
 elsif lower(w.name) like '%бухал%' or lower(w.name) like '%тръб%' then msg:=ap.username||' замахва с '||w.name||' и разклаща '||tp.username||'.';
 else msg:=ap.username||' използва '||w.name||' срещу '||tp.username||'.'; end if;
 if crit and hp_after>0 then msg:=msg||' Критичен удар!'; end if;
 if hp_after=0 then msg:=msg||' '||tp.username||' е нокаутиран!'; elsif dmg>0 and hp_after<=t.battle_max_hp*0.25 then msg:=msg||' '||tp.username||' едва се държи на крака.'; end if;
 update public.gang_battle_entries set battle_hp=hp_after,knocked_out=(hp_after=0) where battle_id=b.id and user_id=t.user_id;
 update public.gang_battle_entries set total_damage=total_damage+dmg,last_attack_at=now(),molotov_used=(molotov_used or lower(coalesce(w.name,''))=lower('Молотов')) where battle_id=b.id and user_id=a.user_id;
 insert into public.gang_battle_events(battle_id,actor_id,target_id,event_type,message,damage,target_hp,special_effect,weapon_item_id,payload) values(b.id,a.user_id,t.user_id,case when hp_after=0 then 'knockout' when missed then 'miss' when blocked then 'block' when crit then 'critical' else 'attack' end,msg,dmg,hp_after,special,w.id,jsonb_build_object('critical',crit,'blocked',blocked,'missed',missed,'weapon',w.name));
 if w.id is not null and w.consumed_on_use then if qty<=1 then delete from public.inventory where user_id=a.user_id and item_id=w.id; else update public.inventory set quantity=quantity-1 where user_id=a.user_id and item_id=w.id; end if; end if;
 select not exists(select 1 from public.gang_battle_entries where battle_id=b.id and gang_id=t.gang_id and knocked_out=false and battle_hp>0) into all_down;
 if all_down then result:=public.finish_gang_battle(b.id);return result||jsonb_build_object('damage',dmg,'target_hp',hp_after,'message',msg,'finished',true); end if;
 return jsonb_build_object('damage',dmg,'target_hp',hp_after,'message',msg,'critical',crit,'blocked',blocked,'missed',missed,'special_effect',special,'finished',false,'cooldown_seconds',5);
end $$;

revoke execute on function public.create_gang_battle(bigint,integer) from public,anon;
revoke execute on function public.join_gang_battle(bigint) from public,anon;
revoke execute on function public.finish_gang_battle(bigint) from public,anon;
revoke execute on function public.attack_gang_battle(bigint,uuid,bigint) from public,anon;
grant execute on function public.create_gang_battle(bigint,integer) to authenticated;
grant execute on function public.join_gang_battle(bigint) to authenticated;
grant execute on function public.finish_gang_battle(bigint) to authenticated;
grant execute on function public.attack_gang_battle(bigint,uuid,bigint) to authenticated;
