-- Tactical battles + Mafia system
-- Additive migration only. No destructive DDL.

alter table public.items add column if not exists combat_effect text;
alter table public.items add column if not exists combat_effect_value integer not null default 0;
alter table public.items add column if not exists consumed_on_use boolean not null default false;

alter table public.battles add column if not exists attacker_weapon_id bigint references public.items(id);
alter table public.battles add column if not exists defender_weapon_id bigint references public.items(id);
alter table public.battles add column if not exists attacker_score numeric;
alter table public.battles add column if not exists defender_score numeric;
alter table public.battles add column if not exists special_effect text;
alter table public.battles add column if not exists details jsonb not null default '{}'::jsonb;

create table if not exists public.battle_events (
  id bigint generated by default as identity primary key,
  battle_id bigint not null references public.battles(id) on delete cascade,
  actor_id uuid references public.profiles(id),
  event_type text not null,
  message text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists battle_events_battle_id_idx on public.battle_events(battle_id,id);

create table if not exists public.game_notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  battle_id bigint references public.battles(id) on delete cascade,
  notification_type text not null,
  title text not null,
  body text not null,
  read_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists game_notifications_user_idx on public.game_notifications(user_id,read_at,created_at desc);

create table if not exists public.mafias (
  id bigint generated by default as identity primary key,
  name text not null unique,
  leader_gang_id bigint not null references public.gangs(id),
  reputation integer not null default 0,
  created_by uuid not null references public.profiles(id),
  created_at timestamptz not null default now()
);
create table if not exists public.mafia_gangs (
  mafia_id bigint not null references public.mafias(id) on delete cascade,
  gang_id bigint not null unique references public.gangs(id) on delete cascade,
  joined_at timestamptz not null default now(),
  primary key(mafia_id,gang_id)
);
create table if not exists public.mafia_invites (
  id bigint generated by default as identity primary key,
  mafia_id bigint not null references public.mafias(id) on delete cascade,
  gang_id bigint not null references public.gangs(id) on delete cascade,
  invited_by uuid not null references public.profiles(id),
  status text not null default 'pending' check(status in ('pending','accepted','declined')),
  created_at timestamptz not null default now(),
  responded_at timestamptz,
  unique(mafia_id,gang_id)
);
create table if not exists public.mafia_wars (
  id bigint generated by default as identity primary key,
  challenger_mafia_id bigint not null references public.mafias(id),
  defender_mafia_id bigint not null references public.mafias(id),
  status text not null default 'planned' check(status in ('planned','open','finished','cancelled')),
  challenger_score integer not null default 0,
  defender_score integer not null default 0,
  winner_mafia_id bigint references public.mafias(id),
  starts_at timestamptz,
  ends_at timestamptz,
  created_at timestamptz not null default now(),
  check(challenger_mafia_id <> defender_mafia_id)
);

alter table public.battle_events enable row level security;
alter table public.game_notifications enable row level security;
alter table public.mafias enable row level security;
alter table public.mafia_gangs enable row level security;
alter table public.mafia_invites enable row level security;
alter table public.mafia_wars enable row level security;

grant select on public.battle_events to authenticated;
grant select,update on public.game_notifications to authenticated;
grant select on public.mafias,public.mafia_gangs,public.mafia_invites,public.mafia_wars to authenticated;

do $$ begin
 if not exists(select 1 from pg_policies where schemaname='public' and tablename='battle_events' and policyname='battle participants read events') then
  create policy "battle participants read events" on public.battle_events for select to authenticated
  using(exists(select 1 from public.battles b where b.id=battle_id and (b.attacker=(select auth.uid()) or b.defender=(select auth.uid()))));
 end if;
 if not exists(select 1 from pg_policies where schemaname='public' and tablename='game_notifications' and policyname='own notifications read') then
  create policy "own notifications read" on public.game_notifications for select to authenticated using((select auth.uid())=user_id);
 end if;
 if not exists(select 1 from pg_policies where schemaname='public' and tablename='game_notifications' and policyname='own notifications update') then
  create policy "own notifications update" on public.game_notifications for update to authenticated
  using((select auth.uid())=user_id) with check((select auth.uid())=user_id);
 end if;
 if not exists(select 1 from pg_policies where schemaname='public' and tablename='mafias' and policyname='mafias readable') then
  create policy "mafias readable" on public.mafias for select to authenticated using(true);
 end if;
 if not exists(select 1 from pg_policies where schemaname='public' and tablename='mafia_gangs' and policyname='mafia gangs readable') then
  create policy "mafia gangs readable" on public.mafia_gangs for select to authenticated using(true);
 end if;
 if not exists(select 1 from pg_policies where schemaname='public' and tablename='mafia_invites' and policyname='mafia invites visible to involved gangs') then
  create policy "mafia invites visible to involved gangs" on public.mafia_invites for select to authenticated using(
   exists(select 1 from public.gang_members gm where gm.user_id=(select auth.uid()) and (gm.gang_id=gang_id or gm.gang_id in (select leader_gang_id from public.mafias m where m.id=mafia_id)))
  );
 end if;
 if not exists(select 1 from pg_policies where schemaname='public' and tablename='mafia_wars' and policyname='mafia wars readable') then
  create policy "mafia wars readable" on public.mafia_wars for select to authenticated using(true);
 end if;
end $$;

insert into public.items(name,slot,price,strength_bonus,defense_bonus,luck_bonus,min_level,description,item_type,energy_restore,attack_bonus,rarity,combat_effect,combat_effect_value,consumed_on_use)
select 'Молотов','weapon',45,0,0,1,2,'Еднократно оръжие. Нанася допълнителен огнен ефект в боя.','weapon',0,6,'rare','burn',8,true
where not exists(select 1 from public.items where lower(name)=lower('Молотов'));

create or replace function public.buy_item(target_item bigint)
returns jsonb language plpgsql security definer set search_path='public' as $$
declare p public.profiles; it public.items;
begin
 if auth.uid() is null then raise exception 'not authenticated'; end if;
 select * into p from public.profiles where id=auth.uid() for update;
 select * into it from public.items where id=target_item;
 if it.id is null then raise exception 'Няма такъв предмет'; end if;
 if p.level < it.min_level then raise exception 'Нивото ти е ниско'; end if;
 if p.money < it.price then raise exception 'Нямаш достатъчно пари'; end if;
 if it.item_type<>'consumable' and not it.consumed_on_use and exists(select 1 from public.inventory where user_id=auth.uid() and item_id=target_item) then raise exception 'Вече имаш този предмет'; end if;
 update public.profiles set money=money-it.price where id=auth.uid();
 insert into public.inventory(user_id,item_id,quantity) values(auth.uid(),target_item,1)
 on conflict(user_id,item_id) do update set quantity=public.inventory.quantity+1;
 insert into public.action_log(user_id,action_type,message,money_change,respect_change) values(auth.uid(),'shop','Купи '||it.name,-it.price,0);
 return jsonb_build_object('ok',true,'item',it.name);
end $$;

create or replace function public.fight_player(opponent uuid,p_weapon_item_id bigint)
returns jsonb language plpgsql security definer set search_path='public' as $$
declare
 a public.profiles; d public.profiles; act public.activities; weapon public.items; defender_weapon public.items;
 weapon_qty int:=0; a_str int; a_def int; a_luck int; d_str int; d_def int; d_luck int;
 ascore numeric; dscore numeric; won boolean; rep int; cash int; bid bigint; burn_damage int:=0; effect text:=null;
begin
 if auth.uid() is null then raise exception 'not authenticated'; end if;
 if opponent=auth.uid() then raise exception 'Не можеш да нападнеш себе си'; end if;
 select * into act from public.activities where user_id=auth.uid();
 if act.user_id is not null then
  if act.ends_at<=now() then raise exception 'Имаш приключила дейност. Вземи наградата първо.'; else raise exception 'Не можеш да се биеш, докато героят е зает.'; end if;
 end if;
 perform public.regen_me();
 select * into a from public.profiles where id=auth.uid() for update;
 select * into d from public.profiles where id=opponent for update;
 if d.id is null then raise exception 'Играчът не съществува'; end if;
 if a.energy<20 then raise exception 'Нямаш достатъчно енергия'; end if;
 if p_weapon_item_id is not null then
  select i.* into weapon from public.inventory v join public.items i on i.id=v.item_id where v.user_id=a.id and v.item_id=p_weapon_item_id and i.item_type='weapon';
  if weapon.id is null then raise exception 'Не притежаваш това оръжие'; end if;
  select quantity into weapon_qty from public.inventory where user_id=a.id and item_id=weapon.id for update;
 end if;
 select a.strength+coalesce(sum(i.strength_bonus+i.attack_bonus),0),a.defense+coalesce(sum(i.defense_bonus),0),a.luck+coalesce(sum(i.luck_bonus),0)
 into a_str,a_def,a_luck from public.inventory v join public.items i on i.id=v.item_id where v.user_id=a.id and v.equipped=true and (p_weapon_item_id is null or i.slot<>'weapon' or i.id=p_weapon_item_id);
 if a_str is null then a_str:=a.strength; a_def:=a.defense; a_luck:=a.luck; end if;
 if weapon.id is not null and not exists(select 1 from public.inventory where user_id=a.id and item_id=weapon.id and equipped=true) then
  a_str:=a_str+weapon.strength_bonus+weapon.attack_bonus; a_def:=a_def+weapon.defense_bonus; a_luck:=a_luck+weapon.luck_bonus;
 end if;
 select i.* into defender_weapon from public.inventory v join public.items i on i.id=v.item_id where v.user_id=d.id and v.equipped=true and i.item_type='weapon' order by i.attack_bonus desc limit 1;
 select d.strength+coalesce(sum(i.strength_bonus+i.attack_bonus),0),d.defense+coalesce(sum(i.defense_bonus),0),d.luck+coalesce(sum(i.luck_bonus),0)
 into d_str,d_def,d_luck from public.inventory v join public.items i on i.id=v.item_id where v.user_id=d.id and v.equipped=true;
 if d_str is null then d_str:=d.strength; d_def:=d.defense; d_luck:=d.luck; end if;
 ascore:=a_str*1.5+a_def+a_luck*0.7+random()*18; dscore:=d_str*1.5+d_def+d_luck*0.7+random()*18;
 if weapon.combat_effect='burn' then effect:='burn'; burn_damage:=greatest(1,weapon.combat_effect_value); ascore:=ascore+burn_damage; end if;
 won:=ascore>=dscore; update public.profiles set energy=energy-20 where id=a.id;
 if won then
  rep:=4+floor(random()*5)::int; cash:=5+floor(random()*8)::int;
  update public.profiles set wins=wins+1,respect=respect+rep,money=money+cash where id=a.id;
  update public.profiles set losses=losses+1,hp=greatest(10,hp-10-burn_damage) where id=d.id;
  insert into public.battles(attacker,defender,winner,respect_change,money_change,attacker_weapon_id,defender_weapon_id,attacker_score,defender_score,special_effect,details)
  values(a.id,d.id,a.id,rep,cash,weapon.id,defender_weapon.id,round(ascore,1),round(dscore,1),effect,jsonb_build_object('energy_cost',20,'burn_damage',burn_damage)) returning id into bid;
 else
  rep:=0; cash:=0;
  update public.profiles set losses=losses+1,hp=greatest(10,hp-15) where id=a.id;
  update public.profiles set wins=wins+1,respect=respect+2,hp=greatest(10,hp-burn_damage) where id=d.id;
  insert into public.battles(attacker,defender,winner,respect_change,money_change,attacker_weapon_id,defender_weapon_id,attacker_score,defender_score,special_effect,details)
  values(a.id,d.id,d.id,0,0,weapon.id,defender_weapon.id,round(ascore,1),round(dscore,1),effect,jsonb_build_object('energy_cost',20,'burn_damage',burn_damage)) returning id into bid;
 end if;
 insert into public.battle_events(battle_id,actor_id,event_type,message,payload) values
  (bid,a.id,'attack',a.username||' нападна '||d.username,jsonb_build_object('weapon',coalesce(weapon.name,'Без оръжие')));
 if weapon.id is not null then insert into public.battle_events(battle_id,actor_id,event_type,message,payload) values(bid,a.id,'weapon',a.username||' използва '||weapon.name,jsonb_build_object('weapon_id',weapon.id)); end if;
 if effect='burn' then insert into public.battle_events(battle_id,actor_id,event_type,message,payload) values(bid,a.id,'special','🔥 Молотовът подпали противника',jsonb_build_object('extra_damage',burn_damage)); end if;
 insert into public.battle_events(battle_id,actor_id,event_type,message,payload) values(bid,case when won then a.id else d.id end,'result',(case when won then a.username else d.username end)||' спечели битката',jsonb_build_object('attacker_score',round(ascore,1),'defender_score',round(dscore,1),'respect',rep,'money',cash));
 insert into public.game_notifications(user_id,battle_id,notification_type,title,body) values
  (d.id,bid,'attacked','⚠️ Нападнаха те!',a.username||' те нападна'||case when weapon.id is not null then ' с '||weapon.name else '' end||'.'),
  (a.id,bid,'battle_result',case when won then '🏆 Победа!' else '💥 Загуба' end,'Битката срещу '||d.username||' приключи. Натисни, за да я отвориш.'),
  (d.id,bid,'battle_result',case when won then '💥 Загуба' else '🏆 Победа!' end,'Битката срещу '||a.username||' приключи. Натисни, за да я отвориш.');
 if weapon.id is not null and weapon.consumed_on_use then
  if weapon_qty<=1 then delete from public.inventory where user_id=a.id and item_id=weapon.id;
  else update public.inventory set quantity=quantity-1 where user_id=a.id and item_id=weapon.id; end if;
 end if;
 update public.profiles set level=greatest(level,1+floor(respect/25.0)::int) where id in(a.id,d.id);
 return jsonb_build_object('battle_id',bid,'won',won,'respect',rep,'money',cash,'attacker_score',round(ascore,1),'defender_score',round(dscore,1),'weapon',weapon.name,'special_effect',effect,'special_effect_value',burn_damage);
end $$;

create or replace function public.fight_player(opponent uuid)
returns jsonb language plpgsql security definer set search_path='public' as $$ begin return public.fight_player(opponent,null); end $$;

create or replace function public.create_mafia(p_name text)
returns jsonb language plpgsql security definer set search_path='public' as $$
declare gm public.gang_members; mid bigint;
begin
 if auth.uid() is null then raise exception 'not authenticated'; end if;
 select * into gm from public.gang_members where user_id=auth.uid();
 if gm.user_id is null or gm.role<>'leader' then raise exception 'Само лидер на банда може да създаде Мафия.'; end if;
 if exists(select 1 from public.mafia_gangs where gang_id=gm.gang_id) then raise exception 'Бандата вече е в Мафия.'; end if;
 if length(trim(p_name))<3 then raise exception 'Името трябва да е поне 3 символа.'; end if;
 insert into public.mafias(name,leader_gang_id,created_by) values(trim(p_name),gm.gang_id,auth.uid()) returning id into mid;
 insert into public.mafia_gangs(mafia_id,gang_id) values(mid,gm.gang_id);
 return jsonb_build_object('id',mid,'name',trim(p_name),'leader_gang_id',gm.gang_id);
end $$;

create or replace function public.invite_mafia_gang(p_gang_id bigint)
returns jsonb language plpgsql security definer set search_path='public' as $$
declare gm public.gang_members; m public.mafias; iid bigint;
begin
 if auth.uid() is null then raise exception 'not authenticated'; end if;
 select * into gm from public.gang_members where user_id=auth.uid();
 select mm.* into m from public.mafias mm where mm.leader_gang_id=gm.gang_id;
 if gm.role<>'leader' or m.id is null then raise exception 'Само лидерската банда на Мафията може да кани.'; end if;
 if p_gang_id=gm.gang_id then raise exception 'Тази банда вече е лидерска.'; end if;
 if exists(select 1 from public.mafia_gangs where gang_id=p_gang_id) then raise exception 'Бандата вече е в Мафия.'; end if;
 insert into public.mafia_invites(mafia_id,gang_id,invited_by) values(m.id,p_gang_id,auth.uid())
 on conflict(mafia_id,gang_id) do update set status='pending',invited_by=excluded.invited_by,created_at=now(),responded_at=null returning id into iid;
 return jsonb_build_object('invite_id',iid,'mafia_id',m.id,'gang_id',p_gang_id);
end $$;

create or replace function public.respond_mafia_invite(p_invite_id bigint,p_accept boolean)
returns jsonb language plpgsql security definer set search_path='public' as $$
declare gm public.gang_members; inv public.mafia_invites; m public.mafias;
begin
 if auth.uid() is null then raise exception 'not authenticated'; end if;
 select * into gm from public.gang_members where user_id=auth.uid();
 if gm.user_id is null or gm.role<>'leader' then raise exception 'Само лидерът на поканената банда може да отговори.'; end if;
 select * into inv from public.mafia_invites where id=p_invite_id for update;
 if inv.id is null or inv.gang_id<>gm.gang_id or inv.status<>'pending' then raise exception 'Невалидна покана.'; end if;
 if p_accept then
  if exists(select 1 from public.mafia_gangs where gang_id=gm.gang_id) then raise exception 'Бандата вече е в Мафия.'; end if;
  insert into public.mafia_gangs(mafia_id,gang_id) values(inv.mafia_id,gm.gang_id);
  update public.mafia_invites set status='accepted',responded_at=now() where id=inv.id;
  select * into m from public.mafias where id=inv.mafia_id;
  return jsonb_build_object('accepted',true,'mafia_id',m.id,'name',m.name);
 else
  update public.mafia_invites set status='declined',responded_at=now() where id=inv.id;
  return jsonb_build_object('accepted',false);
 end if;
end $$;

create or replace function public.leave_mafia()
returns jsonb language plpgsql security definer set search_path='public' as $$
declare gm public.gang_members; mg public.mafia_gangs; m public.mafias; cnt int;
begin
 if auth.uid() is null then raise exception 'not authenticated'; end if;
 select * into gm from public.gang_members where user_id=auth.uid();
 if gm.user_id is null or gm.role<>'leader' then raise exception 'Само лидерът на бандата може да я извади от Мафия.'; end if;
 select * into mg from public.mafia_gangs where gang_id=gm.gang_id;
 if mg.gang_id is null then raise exception 'Бандата не е в Мафия.'; end if;
 select * into m from public.mafias where id=mg.mafia_id;
 if m.leader_gang_id=gm.gang_id then raise exception 'Лидерската банда не може да напусне. Първо трябва да предаде лидерството.'; end if;
 delete from public.mafia_gangs where mafia_id=mg.mafia_id and gang_id=gm.gang_id;
 select count(*) into cnt from public.mafia_gangs where mafia_id=mg.mafia_id;
 return jsonb_build_object('left',true,'remaining_gangs',cnt);
end $$;

revoke execute on function public.buy_item(bigint) from public,anon;
revoke execute on function public.fight_player(uuid,bigint) from public,anon;
revoke execute on function public.fight_player(uuid) from public,anon;
revoke execute on function public.create_mafia(text) from public,anon;
revoke execute on function public.invite_mafia_gang(bigint) from public,anon;
revoke execute on function public.respond_mafia_invite(bigint,boolean) from public,anon;
revoke execute on function public.leave_mafia() from public,anon;
grant execute on function public.buy_item(bigint) to authenticated;
grant execute on function public.fight_player(uuid,bigint) to authenticated;
grant execute on function public.fight_player(uuid) to authenticated;
grant execute on function public.create_mafia(text) to authenticated;
grant execute on function public.invite_mafia_gang(bigint) to authenticated;
grant execute on function public.respond_mafia_invite(bigint,boolean) to authenticated;
grant execute on function public.leave_mafia() to authenticated;
